import type { SupabaseClient } from '@supabase/supabase-js';
import { MessageDirection, ConversationEventType } from '@lib/types';

/**
 * Count the number of unprompted follow-ups ("nudges") sent to a lead since
 * their most recent inbound message.
 *
 * This is what `max_followups` is meant to cap: consecutive nudges to a SILENT
 * lead. We count `followup_sent` events created after the lead's last inbound
 * message, so a genuine back-and-forth doesn't consume the follow-up budget and
 * each new silence resets it. If the lead has never replied (e.g. AI-initiated
 * outreach), every follow-up sent so far counts.
 */
export async function countConsecutiveFollowups(
  db: SupabaseClient,
  conversationId: string,
): Promise<number> {
  const { data: lastInbound } = await db
    .from('messages')
    .select('created_at')
    .eq('conversation_id', conversationId)
    .eq('direction', MessageDirection.Inbound)
    .order('created_at', { ascending: false })
    .limit(1)
    .maybeSingle();

  let query = db
    .from('conversation_events')
    .select('*', { count: 'exact', head: true })
    .eq('conversation_id', conversationId)
    .eq('event_type', ConversationEventType.FollowupSent);

  if (lastInbound?.created_at) {
    query = query.gt('created_at', lastInbound.created_at);
  }

  const { count } = await query;
  return count ?? 0;
}

/**
 * Synthetic trailing user turn appended to the message array on a follow-up.
 *
 * On a follow-up the lead has gone silent, so the conversation ends on the AI's
 * own (assistant) message. Without a final user turn the model just continues /
 * repeats itself. This gives it something to respond to so it produces a fresh
 * nudge instead of re-sending the last message.
 */
export const FOLLOWUP_USER_TURN =
  '[The lead has not replied since your last message. Write a natural follow-up now — do not repeat or rephrase your previous message.]';

/**
 * System-prompt note injected when an AI reply is generated by the follow-up
 * cadence rather than an inbound message. Tells the model the lead has gone
 * quiet and to build on the thread instead of repeating itself, escalating tone
 * from a gentle nudge toward a graceful final check-in as the count approaches
 * the configured max.
 */
export function followupPromptNote(followup: { number: number; total: number }): string {
  const { number, total } = followup;
  const isFinal = total > 0 && number >= total;
  return [
    'FOLLOW-UP NUDGE — the lead has NOT replied since your last message.',
    `This is follow-up ${number}${total > 0 ? ` of ${total}` : ''}.`,
    'Do NOT repeat or rephrase your previous message. Write a brief, natural follow-up that',
    'moves things forward: pick up the thread where it left off, add a little new value or a',
    'light, genuine reason to re-engage, and keep it warm and low-pressure.',
    isFinal
      ? 'This is your LAST follow-up — make it a graceful, no-pressure final check-in that leaves the door open.'
      : 'Keep it light; there is room to follow up again if they stay quiet.',
  ].join(' ');
}
